replicaCount: 1

images:

  auth:
    repository: 360999005537.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-auth
    tag: latest

  streaming:
    repository: 360999005537.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-streaming
    tag: latest

  admin:
    repository: 360999005537.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-admin
    tag: latest

  chat:
    repository: 360999005537.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-chat
    tag: latest

  frontend:
    repository: 360999005537.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-frontend
    tag: latest

services:

  auth:
    port: 3001

  streaming:
    port: 3002

  admin:
    port: 3003

  chat:
    port: 3004

  frontend:
    port: 80

mongo:
  image: mongo:6
  port: 27017
  database: streamingapp