apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chat
spec:
  selector:
    app: {{ .Release.Name }}-chat
  ports:
    - port: {{ .Values.services.chat.port }}
      targetPort: {{ .Values.services.chat.port }}
  type: ClusterIP
