apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.database | quote }}